#!/bin/sh
#
#-- remove old configuration files
#
rm -f depcomp missing install-sh mkinstalldirs libtool acconfig.h
rm -f aclocal.m4 configure Makefile.in config.guess config.cache ltmain.sh config.sub
rm -rf autom4te.cache Makefile Makefile.in *.lo
#
#-- regenerate configuration
#
aclocal 2> /dev/null
libtoolize --force
automake --foreign --copy --add-missing
autoconf
#
#-- end
